## robot moviment
# position in joy axes vector
axis_angular: 0
axis_linear: 1

# scale of moviment
scale_angular: 0.15
scale_angular_turbo: 0.7
scale_linear: 0.3
scale_linear_turbo: 1.0

# buttons enable
enable_button: 6
enable_turbo_button: 7

## camera moviment
step_pan: 30
step_tilt: 30
step_zoom: 100

# button for moviment
pan_positive_button: 1
pan_negative_button: 3
tilt_positive_button: 0
tilt_negative_button: 2
zoom_positive_button: 5
zoom_negative_button: 4
